server:
  port: 8080
  servlet:
    context-path: /demo
spring:
  swagger:
    enabled: true
    title: spring-boot-swaggerbeauty
    base-package: com.dyz.swaggerbeauty.controller
    description: 这是一个简单的 swaggerbeauty Demo
    version: 1.0.0-SNAPSHOT
    contact:
      name: dyz
      email: 137025xxx@qq.com
      url: https://blog.csdn.net/MICHAELKING1
    # swagger扫描的基础包，默认：全扫描
    # base-package:
    # 需要处理的基础URL规则，默认：/**
    # base-path:
    # 需要排除的URL规则，默认：空
    # exclude-path:
    security:
      # 是否启用 swagger 登录验证
      filter-plugin: true
      username: dyz
      password: dyz123
    global-response-messages:
      GET[0]:
        code: 400
        message: Bad Request，请求参数不对
      GET[1]:
        code: 404
        message: NOT FOUND，请求路径不对
      GET[2]:
        code: 500
        message: ERROR，程序内部错误
      POST[0]:
        code: 400
        message: Bad Request，请求参数不对
      POST[1]:
        code: 404
        message: NOT FOUND，请求路径不对
      POST[2]:
        code: 500
        message: ERROR，程序内部错误
